
INSERT INTO person(first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES ('Lars','de Graaf', '1989-11-26', 'Belgium','Male', 'lalalalalalal', 0xFF782B,'Actor');
INSERT INTO person(first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES ('Matthias','Schoenaerts', '1982-06-12', 'Belgium','Male', 'dit is schoenaerts zijn biography', 'http://ia.media-imdb.com/images/M/MV5BMjMyNTQ0MDgwOF5BMl5BanBnXkFtZTcwOTUxNzA3OA@@._V1_UY317_CR12,0,214,317_AL_.jpg','Actor');
INSERT INTO person(first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES ('jamie','foxx', '1982-06-12', 'USA','Male', 'WTF NIGGER ON A HORSE', 'http://www.dinnerpartydownload.org/wp-content/uploads/2013/04/jamie-foxx-don-cheadle-naacp-image-awards-2013-04.jpg','Actor');
INSERT INTO person(first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES ('James','Gandolfini', '1961-09-18', 'USA','Male', 'the role that brought him worldwide fame and accolades was as complex Mafia boss Tony Soprano in HBO''s smash hit series The Sopranos . He died unexpectedly of a heart attack in 2013 while vacationing in Italy.','http://timothywhite.com/sites/default/files/images/portfolio/141_James-Gandolfini.jpg' ,'Actor');


INSERT INTO film(title, genre,trailer,summary) Values ('Test','Action','test','test');
INSERT INTO film(title, genre,trailer,summary,image) Values ('Scarface','Action','https://www.youtube.com/embed/7pQQHnqBa2E','Tony Montana is going to rule the gangsterworld','https://kjambor.files.wordpress.com/2011/10/scarface-poster-movie-poster-4.jpg');
INSERT INTO film(title, genre,trailer,summary,image) Values ('Dude Where Is My Car','Comedy','https://www.youtube.com/embed/d1wuijgeaaY','2 mannen die na ee nscheve avond niet meer weten wat er gebeurd is, en er zijn vreemde dingen gebeurd','http://ia.media-imdb.com/images/M/MV5BMTg4ODcxOTgyOV5BMl5BanBnXkFtZTcwODI0NTI1MQ@@._V1_SX640_SY720_.jpg');
INSERT INTO film(title, genre,trailer,summary,image) Values ('Shutters Island','Thriller','https://www.youtube.com/embed/5iaYLCiq5RM','dit is de summary van de film Shutter island','http://theopinionmag.com/wp-content/uploads/2012/01/Shutter-Island-dvd.jpg');
INSERT INTO film(title, genre,trailer,summary,image) Values ('Django Unchained','Action','https://www.youtube.com/embed/eUdM9vrCbow','de slaaf django wordt vrijgekocht en gaat mee op jacht met bountyhunter','http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX640_SY720_.jpg');