
INSERT INTO person(id, first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES (1,'Lars','de Graaf', '1989-11-26', 'Belgium','Male', 'lalalalalalal', 'https://scontent-ams3-1.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/11149402_101179980213781_7459203682729654237_n.jpg?oh=c360157b77ec494148f4933a18aede17&oe=560E52E6','Actor');
INSERT INTO person(id, first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES (2,'Matthias','Schoenaerts', '1982-06-12', 'Belgium','Male', 'dit is schoenaerts zijn biography', 'http://ia.media-imdb.com/images/M/MV5BMjMyNTQ0MDgwOF5BMl5BanBnXkFtZTcwOTUxNzA3OA@@._V1_UY317_CR12,0,214,317_AL_.jpg','Actor');
INSERT INTO person(id, first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES (3,'jamie','foxx', '1982-06-12', 'USA','Male', 'WTF NIGGER ON A HORSE', 'http://www.dinnerpartydownload.org/wp-content/uploads/2013/04/jamie-foxx-don-cheadle-naacp-image-awards-2013-04.jpg','Actor');
INSERT INTO person(id, first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES (4,'James','Gandolfini', '1961-09-18', 'USA','Male', 'the role that brought him worldwide fame and accolades was as complex Mafia boss Tony Soprano in HBO''s smash hit series The Sopranos . He died unexpectedly of a heart attack in 2013 while vacationing in Italy.','http://timothywhite.com/sites/default/files/images/portfolio/141_James-Gandolfini.jpg' ,'Actor');
INSERT INTO person(id, first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES (5,'Christoph','Waltz', '1956-10-04', 'AUSTRIA','Male', 'Christoph Waltz was born in Vienna, Austria, to Elisabeth Urbancic, an Austrian-born costume designer, and Johannes Waltz, a German-born stage builder. ','http://wallpaperprime.net/wp-content/uploads/7_Christoph_Waltz-600x400.jpg' ,'Actor');
INSERT INTO person(id, first_name,last_name, birthday, country, gender, biography, picture,dtype ) VALUES (6,'Leonardo','DiCaprio', '1974-11-11', 'USA','Male', 'Few actors in the world have had a career quite as diverse as Leonardo DiCaprios. DiCaprio has gone from relatively humble beginnings, as a supporting cast member of the sitcom Growing Pains','http://ia.media-imdb.com/images/M/MV5BMjI0MTg3MzI0M15BMl5BanBnXkFtZTcwMzQyODU2Mw@@._V1_UY317_CR10,0,214,317_AL_.jpg' ,'Actor');

INSERT INTO film(id, title, genre,trailer,summary,image,flength) Values (1,'Scarface','Action','https://www.youtube.com/embed/7pQQHnqBa2E','Tony Montana is going to rule the gangsterworld','https://kjambor.files.wordpress.com/2011/10/scarface-poster-movie-poster-4.jpg','170 min');
INSERT INTO film(id, title, genre,trailer,summary,image,flength) Values (2,'Dude Where Is My Car','Comedy','https://www.youtube.com/embed/d1wuijgeaaY','2 mannen die na ee nscheve avond niet meer weten wat er gebeurd is, en er zijn vreemde dingen gebeurd','http://ia.media-imdb.com/images/M/MV5BMTg4ODcxOTgyOV5BMl5BanBnXkFtZTcwODI0NTI1MQ@@._V1_SX640_SY720_.jpg','83 min');
INSERT INTO film(id, title, genre,trailer,summary,image,flength) Values (3,'Shutters Island','Thriller','https://www.youtube.com/embed/5iaYLCiq5RM','dit is de summary van de film Shutter island','http://theopinionmag.com/wp-content/uploads/2012/01/Shutter-Island-dvd.jpg','120 min');
INSERT INTO film(id, title, genre,trailer,summary,image,flength) Values (4,'Django Unchained','Action','https://www.youtube.com/embed/eUdM9vrCbow','de slaaf django wordt vrijgekocht en gaat mee op jacht met bountyhunter','http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX640_SY720_.jpg','135 min');

INSERT  INTO film_character(id, character_name, actor_id,film_id) VALUES (1,'Django', 3, 4);
INSERT  INTO film_character(id, character_name, actor_id,film_id) VALUES (2,'Dr King Schultz', 5, 4);
INSERT  INTO film_character(id, character_name, actor_id,film_id) VALUES (3,'Calvin Candie', 6, 4);
INSERT  INTO film_character(id, character_name, actor_id,film_id) VALUES (4,'Teddy Daniels', 6, 3);

